rubizza-camp/AgileCli_Server

.gitignore, server/Gemfile, server/Gemfile.lock, server/spec/helpers/welcome_helper_spec.rb, server/spec/rails_helper.rb, server/spec/spec_helper.rb
https://trello.com/c/2ZcyINTO/24-add-simplecov-to-server
=> Setup simplecov

server/config/application.rb, server/config/database.yml
https://trello.com/c/LyqS4eqg/34-set-up-database
=> Configure db

.circleci/config.yml
=> Add rspec config

app/controllers/api/v1/projects_controller.rb, app/serializers/api/v1/project_serializer.rb, config/routes.rb, db/seeds.rb
=> Add projects to api

app/serializers/api/v1/user_serializer.rb, db/migrate/20190816065154_delete_name_from_user.rb, db/schema.rb
=> delete name from users

app/controllers/api/v1/projects_controller.rb
=> destroy api

app/controllers/api/v1/projects_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/project.rb
=> REFACTORING CODE BY NIKITA

app/controllers/api/v1/projects_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/project.rb
=> Fix minor errors

Gemfile, Gemfile.lock, app/controllers/api/v1/projects_controller.rb, app/controllers/api/v1/users_controller.rb, app/serializers/api/v1/base_serializer.rb, config/initializers/active_model_serializers.rb
=> Add fast json

app/assets/stylesheets/dictionary.scss, app/assets/stylesheets/manifesto.scss, app/views/dictionary/dictionary.html.erb, config/application.rb
Dictionary view
Add view to dictionary and font to server
=> Agile dictionary

app/controllers/login_controller.rb, app/views/login/signin.html.erb, config/routes.rb
=> Fix render after login

app/controllers/api/v1/tickets_controller.rb, app/models/project.rb, app/models/user.rb, app/serializers/api/v1/ticket_serializer.rb, config/routes.rb, db/migrate/20190826112604_edit_tickets.rb, db/schema.rb
=> tickets api

app/controllers/api/v1/tickets_controller.rb, app/serializers/api/v1/ticket_serializer.rb
=> tickets_api

app/controllers/api/v1/projects_controller.rb, app/controllers/api/v1/tickets_controller.rb
=> api for tickets and some api for projects

app/views/invite_mailer/sample_email.html.erb, app/views/invite_mailer/sample_email.text.erb, app/views/welcome_mailer/sample_email.html.erb, app/views/welcome_mailer/sample_email.text.erb, config/database.yml
=> Mailers views

.gitignore, app/controllers/api/v1/events_controller.rb, app/models/event.rb, app/serializers/api/v1/event_serializer.rb, db/migrate/20190828080905_new_time_in_events.rb, db/schema.rb
=> Events api

app/controllers/api/v1/events_controller.rb, app/controllers/api/v1/userproject_controller.rb, app/models/event.rb, db/migrate/20190829084558_remove_freq_in_events.rb, db/schema.rb
=> create invite users and remove column in events

app/controllers/api/v1/tickets_controller.rb, app/serializers/api/v1/ticket_serializer.rb, db/migrate/20190829105304_status_in_tickets.rb, db/schema.rb
=> status in ticket

app/controllers/api/v1/tickets_controller.rb, app/serializers/api/v1/ticket_serializer.rb, db/migrate/20190830064646_add_owner_tickets.rb, db/schema.rb
=> add owner in tickets

app/controllers/api/v1/tickets_controller.rb
=> change ticket status

app/controllers/api/v1/tickets_controller.rb, app/serializers/api/v1/event_serializer.rb
=> refactor code in tickets controller and delete frequency in events

app/assets/stylesheets/application.scss, app/assets/stylesheets/homepage.scss, app/javascript/components/Ticket.js, app/views/layouts/application.html.erb, app/views/projects/show.html.erb
=> Project page

app/views/projects/show.html.erb
=> add ticket component
